import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { compile } from "json-schema-to-typescript";
import { format } from "prettier";

const root = resolve(import.meta.dirname, "../..");
const COMPILE_OPTIONS = {
  additionalProperties: false,
  bannerComment: "",
  format: false,
  ignoreMinAndMaxItems: true,
};

/** @type {typeof import("./index.d.ts").generateTypes} */
export async function generateTypes({ cargo, output, external, tsTypesFrom }) {
  const document = JSON.parse(
    execFileSync("cargo", ["run", "-q", ...cargo], {
      cwd: root,
      encoding: "utf8",
    }),
  );
  const { declared, imported, tsTypes } = reachable(document);
  if (external) assertDeclaredBy(external, imported);

  const declarations = await Promise.all(
    declared.map((name) =>
      compile(referencedByName(document.$defs[name]), name, COMPILE_OPTIONS),
    ),
  );

  const content = [
    `// @generated by ${relative(root, process.argv[1])} from \`cargo run -q ${cargo.join(" ")}\`. Do not edit.`,
    ...[
      importDeclaration(imported, external?.from),
      importDeclaration(tsTypes, tsTypesFrom),
    ].filter(Boolean),
    "",
    ...declarations,
  ].join("\n");

  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, await format(content, { parser: "typescript" }));
  console.log(`wrote ${relative(root, output)}`);
}

function reachable({ roots, $defs, external = [] }) {
  const externalNames = new Set(external);
  const declared = [];
  const imported = new Set();
  const tsTypes = new Set();
  const pending = [...roots];
  while (pending.length > 0) {
    const name = pending.shift();
    if (declared.includes(name)) continue;
    declared.push(name);
    for (const reference of references($defs[name])) {
      if (externalNames.has(reference)) imported.add(reference);
      else if (reference in $defs) pending.push(reference);
      else tsTypes.add(reference);
    }
  }
  return { declared, imported, tsTypes };
}

function references(schema) {
  const json = JSON.stringify(schema);
  const refs = [...json.matchAll(/"\$ref":"#\/\$defs\/(\w+)"/g)].map(
    ([, name]) => name,
  );
  const tsTypes = [...json.matchAll(/"tsType":"([^"]*)"/g)].flatMap(
    ([, type]) => type.match(/\b[A-Z]\w*/g) ?? [],
  );
  return [...refs, ...tsTypes];
}

// Compiling a type with every `$ref` replaced by the referenced name declares it exactly once, and keeps a `$ref`
// with sibling keywords, such as a field's description, from becoming a numbered copy of the type it references.
function referencedByName(schema) {
  return JSON.parse(JSON.stringify(schema), (_, value) => {
    if (typeof value?.$ref !== "string") return value;
    const { $ref, ...keywords } = value;
    return { ...keywords, tsType: $ref.replace("#/$defs/", "") };
  });
}

function assertDeclaredBy({ from, schema }, names) {
  const declared = JSON.parse(readFileSync(schema, "utf8")).$defs;
  const missing = [...names].filter((name) => !(name in declared));
  if (missing.length > 0) {
    throw new Error(
      `${from} does not declare ${missing.join(", ")}; update it to match the Rust types`,
    );
  }
}

function importDeclaration(names, from) {
  if (names.size === 0) return undefined;
  if (from === undefined) {
    throw new Error(`no module to import ${[...names].join(", ")} from`);
  }
  return `import type { ${[...names].sort().join(", ")} } from "${from}";`;
}
