import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

const root = resolve(import.meta.dirname, "../../..");
const GENERATED_NOTICE =
  "Generated by pnpm --filter @aether-agent/sdk generate:types. Do not edit manually.";
const TYPE_OPTIONS = {
  bannerComment: "",
  cwd: root,
  format: false,
  ignoreMinAndMaxItems: true,
};

const document = JSON.parse(
  execFileSync(
    "cargo",
    ["run", "-q", "-p", "aether-schemas"],
    {
      cwd: root,
      encoding: "utf8",
    },
  ),
);

await generateEvalTypes(document);
await generateSettingsTypes(document.AetherSettings);
await generateAcpOptionsTypes(document.AcpOptions);
await generateHeadlessOptionsTypes(document.HeadlessOptions);

async function generateEvalTypes(document) {
  const canonicalSchemaPath = resolve(
    root,
    "website/src/data/aether-eval.schema.json",
  );
  writeText(
    canonicalSchemaPath,
    `${JSON.stringify(
      {
        AgentMessage: document.AgentMessage,
        JudgeRubricResponse: document.JudgeRubricResponse,
        JudgeSummary: document.JudgeSummary,
        JudgeCriterionSpec: document.JudgeCriterionSpec,
      },
      null,
      2,
    )}\n`,
  );

  const parts = await Promise.all(
    [
      ["AgentMessage", document.AgentMessage],
      ["JudgeRubricResponse", document.JudgeRubricResponse],
      ["JudgeSummary", document.JudgeSummary],
      ["JudgeCriterionSpec", document.JudgeCriterionSpec],
    ].map(([title, schema]) =>
      compile(schemaForTypeGeneration(schema, title), title, TYPE_OPTIONS),
    ),
  );

  const content = [
    `// @generated ${GENERATED_NOTICE}\n// Source: aether-schemas.\n`,
    ...parts,
  ].join("\n");

  writeGenerated(
    resolve(import.meta.dirname, "../src/generated/eval-types.ts"),
    content,
  );
}

async function generateSettingsTypes(schema) {
  writeText(
    resolve(root, "website/src/data/aether-settings.schema.json"),
    `${JSON.stringify(schema, null, 2)}\n`,
  );

  const content = `// @generated ${GENERATED_NOTICE}\n// Source: packages/aether-project/src/aether_settings.rs via aether-schemas.\n\n${await compile(
    schemaForTypeGeneration(schema, "AetherSettings"),
    "AetherSettings",
    TYPE_OPTIONS,
  )}`;

  writeGenerated(
    resolve(import.meta.dirname, "../src/generated/aether-settings.ts"),
    content,
  );
}

async function generateAcpOptionsTypes(schema) {
  const content = `// @generated ${GENERATED_NOTICE}\n// Source: packages/aether-cli/src/acp/mod.rs via aether-schemas.\n\n${await compile(
    schemaForTypeGeneration(schema, "AetherAcpOptions"),
    "AetherAcpOptions",
    TYPE_OPTIONS,
  )}`;

  writeGenerated(
    resolve(import.meta.dirname, "../src/generated/aether-acp-options.ts"),
    content,
  );
}

async function generateHeadlessOptionsTypes(schema) {
  const content = `// @generated ${GENERATED_NOTICE}\n// Source: packages/aether-cli/src/headless/mod.rs via aether-schemas.\n\n${await compile(
    schemaForTypeGeneration(schema, "AetherHeadlessCliOptions"),
    "AetherHeadlessCliOptions",
    TYPE_OPTIONS,
  )}`;

  writeGenerated(
    resolve(import.meta.dirname, "../src/generated/aether-headless-options.ts"),
    content,
  );
}

function schemaForTypeGeneration(schema, title) {
  const typeSchema = structuredClone(schema);
  typeSchema.title = title;

  for (const [name, definition] of Object.entries(typeSchema.$defs ?? {})) {
    if (definition && typeof definition === "object") definition.title = name;
  }

  return typeSchema;
}

function writeGenerated(path, content) {
  writeText(path, formatWithPrettier(content, "typescript", root));
  console.log(`wrote ${path}`);
}

function formatWithPrettier(content, parser, root) {
  return execFileSync("pnpm", ["exec", "prettier", "--parser", parser], {
    cwd: root,
    input: content,
    encoding: "utf8",
  });
}

function writeText(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}
