import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { generateTypes } from "@aether-agent/schema-codegen";
import packageJson from "../package.json" with { type: "json" };

const generated = resolve(import.meta.dirname, "../src/generated");

await generateTypes({
  cargo: ["-p", "aether-schemas"],
  output: resolve(generated, "types.ts"),
});

writeFileSync(
  resolve(generated, "sdk-version.ts"),
  `// @generated by packages/aether-sdk/scripts/generate-types.mjs from packages/aether-sdk/package.json. Do not edit.\nexport const SDK_VERSION = ${JSON.stringify(packageJson.version)};\n`,
);
